export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const ADD_NEW_STUDENT_REQUEST = 'ADD_NEW_STUDENT_REQUEST';
export const ADD_NEW_STUDENT_SUCCESS = 'ADD_NEW_STUDENT_SUCCESS';
export const ADD_NEW_STUDENT_FAILURE = 'ADD_NEW_STUDENT_FAILURE';
