export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const ADD_NEW_STUDENT_REQUEST = 'ADD_NEW_STUDENT_REQUEST';
export const ADD_NEW_STUDENT_SUCCESS = 'ADD_NEW_STUDENT_SUCCESS';
export const ADD_NEW_STUDENT_FAILURE = 'ADD_NEW_STUDENT_FAILURE';

export const GET_STUDENT_BY_ID_REQUEST = 'GET_STUDENT_BY_ID_REQUEST';
export const GET_STUDENT_BY_ID_SUCCESS = 'GET_STUDENT_BY_ID_SUCCESS';
export const GET_STUDENT_BY_ID_FAILURE = 'GET_STUDENT_BY_ID_FAILURE';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

export const ADD_NEW_GROUP_REQUEST = 'ADD_NEW_GROUP_REQUEST';
export const ADD_NEW_GROUP_SUCCESS = 'ADD_NEW_GROUP_SUCCESS';
export const ADD_NEW_GROUP_FAILURE = 'ADD_NEW_GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const FETCH_STREAMS_REQUEST = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS';
export const FETCH_STREAMS_FAILURE = 'FETCH_STREAMS_FAILURE';

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE';

export const FETCH_TEACHERS_REQUEST = 'FETCH_TEACHERS_REQUEST';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAILURE = 'FETCH_TEACHERS_FAILURE';

export const DELETE_TEACHER_REQUEST = 'DELETE_TEACHER_REQUEST';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER_FAILURE = 'DELETE_TEACHER_FAILURE';

export const ADD_NEW_TEACHER_REQUEST = 'ADD_NEW_TEACHER_REQUEST';
export const ADD_NEW_TEACHER_SUCCESS = 'ADD_NEW_TEACHER_SUCCESS';
export const ADD_NEW_TEACHER_FAILURE = 'ADD_NEW_TEACHER_FAILURE';

export const GET_TEACHER_BY_ID_REQUEST = 'GET_TEACHER_BY_ID_REQUEST';
export const GET_TEACHER_BY_ID_SUCCESS = 'GET_TEACHER_BY_ID_SUCCESS';
export const GET_TEACHER_BY_ID_FAILURE = 'GET_TEACHER_BY_ID_FAILURE';

export const GET_TEACHERS_BY_SUBJECT_SUCCESS = 'GET_TEACHERS_BY_SUBJECT_SUCCESS';
export const GET_TEACHERS_BY_SUBJECT_FAILURE = 'GET_TEACHERS_BY_SUBJECT_FAILURE';

export const UPDATE_TEACHER_REQUEST = 'UPDATE_TEACHER_REQUEST';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';
export const UPDATE_TEACHER_FAILURE = 'UPDATE_TEACHER_FAILURE';

export const ADD_NEW_PAYMENT_REQUEST = 'ADD_NEW_PAYMENT_REQUEST';
export const ADD_NEW_PAYMENT_SUCCESS = 'ADD_NEW_PAYMENT_SUCCESS';
export const ADD_NEW_PAYMENT_FAILURE = 'ADD_NEW_PAYMENT_FAILURE';

export const GET_PAYMENT_BY_ID_REQUEST = 'GET_PAYMENT_BY_ID_REQUEST';
export const GET_PAYMENT_BY_ID_SUCCESS = 'GET_PAYMENT_BY_ID_SUCCESS';
export const GET_PAYMENT_BY_ID_FAILURE = 'GET_PAYMENT_BY_ID_FAILURE';

export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_FAILURE = 'UPDATE_PAYMENT_FAILURE';

export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE = 'FETCH_SUBJECTS_FAILURE';

export const ADD_NEW_SUBJECT_REQUEST = 'ADD_NEW_SUBJECT_REQUEST';
export const ADD_NEW_SUBJECT_SUCCESS = 'ADD_NEW_SUBJECT_SUCCESS';
export const ADD_NEW_SUBJECT_FAILURE = 'ADD_NEW_SUBJECT_FAILURE';

export const GET_SUBJECT_BY_ID_REQUEST = 'GET_SUBJECT_BY_ID_REQUEST';
export const GET_SUBJECT_BY_ID_SUCCESS = 'GET_SUBJECT_BY_ID_SUCCESS';
export const GET_SUBJECT_BY_ID_FAILURE = 'GET_SUBJECT_BY_ID_FAILURE';

export const UPDATE_SUBJECT_REQUEST = 'UPDATE_SUBJECT_REQUEST';
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_FAILURE = 'UPDATE_SUBJECT_FAILURE';

export const GET_PAYMENTS_BY_STUDENT_ID_REQUEST = 'GET_PAYMENTS_BY_STUDENT_ID_REQUEST';
export const GET_PAYMENTS_BY_STUDENT_ID_SUCCESS = 'GET_PAYMENTS_BY_STUDENT_ID_SUCCESS';
export const GET_PAYMENTS_BY_STUDENT_ID_FAILURE = 'GET_PAYMENTS_BY_STUDENT_ID_FAILURE';

export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DELETE_LESSON_FAILURE = 'DELETE_LESSON_FAILURE';

export const CREATE_LESSONS_REQUEST = 'CREATE_LESSONS_REQUEST';
export const CREATE_LESSONS_SUCCESS = 'CREATE_LESSONS_SUCCESS';
export const CREATE_LESSONS_FAILURE = 'CREATE_LESSONS_FAILURE';

export const FETCH_LESSONS_REQUEST = 'FETCH_LESSONS_REQUEST';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_LESSONS_FAILURE = 'FETCH_LESSONS_FAILURE';

export const ADD_NEW_LESSON_REQUEST = 'ADD_NEW_LESSON_REQUEST';
export const ADD_NEW_LESSON_SUCCESS = 'ADD_NEW_LESSON_SUCCESS';
export const ADD_NEW_LESSON_FAILURE = 'ADD_NEW_LESSON_FAILURE';

export const GET_TEACHERS_LESSONS_REQUEST = 'GET_TEACHERS_LESSONS_REQUEST';
export const GET_TEACHERS_LESSONS_SUCCESS = 'GET_TEACHERS_LESSONS_SUCCESS';
export const GET_TEACHERS_LESSONS_FAILURE = 'GET_TEACHERS_LESSONS_FAILURE';
