export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const ADD_NEW_STUDENT_REQUEST = 'ADD_NEW_STUDENT_REQUEST';
export const ADD_NEW_STUDENT_SUCCESS = 'ADD_NEW_STUDENT_SUCCESS';
export const ADD_NEW_STUDENT_FAILURE = 'ADD_NEW_STUDENT_FAILURE';

export const GET_STUDENT_BY_ID_REQUEST = 'GET_STUDENT_BY_ID_REQUEST';
export const GET_STUDENT_BY_ID_SUCCESS = 'GET_STUDENT_BY_ID_SUCCESS';
export const GET_STUDENT_BY_ID_FAILURE = 'GET_STUDENT_BY_ID_FAILURE';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

export const ADD_NEW_GROUP_REQUEST = 'ADD_NEW_GROUP_REQUEST';
export const ADD_NEW_GROUP_SUCCESS = 'ADD_NEW_GROUP_SUCCESS';
export const ADD_NEW_GROUP_FAILURE = 'ADD_NEW_GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const FETCH_STREAMS_REQUEST = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS';
export const FETCH_STREAMS_FAILURE = 'FETCH_STREAMS_FAILURE';

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE';

export const ADD_NEW_PAYMENT_REQUEST = 'ADD_NEW_PAYMENT_REQUEST';
export const ADD_NEW_PAYMENT_SUCCESS = 'ADD_NEW_PAYMENT_SUCCESS';
export const ADD_NEW_PAYMENT_FAILURE = 'ADD_NEW_PAYMENT_FAILURE';

export const GET_PAYMENT_BY_ID_REQUEST = 'GET_PAYMENT_BY_ID_REQUEST';
export const GET_PAYMENT_BY_ID_SUCCESS = 'GET_PAYMENT_BY_ID_SUCCESS';
export const GET_PAYMENT_BY_ID_SUCCESS = 'GET_PAYMENT_BY_ID_SUCCESS';
